apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/Alwin-K-Thomas/karectl-demo.git
    targetRevision: feature/at-codespace-k3s
    path: gitops/portal
  destination:
    server: https://kubernetes.default.svc
    namespace: portal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
