apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jupyterhub

resources:
  - ingress.yaml

helmCharts:
  - name: jupyterhub
    repo: https://hub.jupyter.org/helm-chart/
    version: 4.0.0
    releaseName: jupyterhub
    namespace: jupyterhub
    valuesFile: values.yaml

patches:
  - patch: |-
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: proxy
